export const LOCATIONS = [
  'ASC-BLAST CARE-IYANA-IPAJA',
  'ASC-BREVA-SANGO',
  'ASC-EJIGBO-EJIGBO',
  'ASC-G-CARE-IYANA-IPAJA',
  'ASC-INNIVE-ALABA',
  'ASC-JUMIKE-MERAN',
  'ASC-MWH-ADENIYI JONES',
  'ASC-SGV-AGBADO',
  'ASC-SULIT HUB-AYOBO',
  'ASC-SULIT HUB-SANGO',
  'ASC-TECHWITCH -AKOWONJO',
  'ASC-VANAPLUS-OJUORE',
] as const;
